package com.model;
// Generated 20 janv. 2018 04:43:44 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "onlineshop")
public class Categorie implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Long idCategorie;
	private String name;
	//private Set<Produit> produits = new HashSet<Produit>(0);

	public Categorie() {
	}

	public Categorie(String name) {
		this.name = name;
	}

/*	public Categorie(String name, Set<Produit> produits) {
		this.name = name;
		this.produits = produits;
	}*/

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCategorie", unique = true, nullable = false)
	public Long getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Long idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Produit> getProduits() {
		return this.produits;
	}

	public void setProduits(Set<Produit> produits) {
		this.produits = produits;
	}*/

}
